Repository 2skydev/Raid-Studio, pull requests merged in 2023-11, with the labels that each got.

#7 필요없는 코드, api, 패키지 제거
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/app/api/auth/[...nextauth]/route.ts
  frontend/src/app/api/clears/cron/route.ts
  frontend/src/app/api/clears/route.ts
  frontend/src/app/api/lostark/characters/[characterName]/route.ts
  frontend/src/app/api/squads/[id]/characters/route.ts
  frontend/src/app/api/squads/[id]/code/route.ts
  frontend/src/app/api/squads/[id]/members/route.ts
  frontend/src/app/api/squads/join/[code]/route.ts
  frontend/src/app/api/squads/route.ts
  frontend/src/app/api/users/me/characters/reload/route.ts
  frontend/src/app/api/users/me/characters/route.ts
  frontend/src/app/api/users/me/route.ts
  frontend/src/app/api/users/me/squads/route.ts
  frontend/src/app/studio/my/characters/page.tsx
  frontend/src/features/user/UserCharacterNameForm/UserCharacterNameForm.tsx
  frontend/src/hooks/useAPI.ts
  frontend/src/libs/auth/index.ts
  frontend/src/libs/db/collections.ts
  frontend/src/libs/db/index.ts
  frontend/src/libs/lostark/api/characters.ts
  frontend/src/libs/lostark/api/index.ts
  frontend/src/libs/lostark/client.ts
  frontend/src/libs/raidStudio/api/clears.ts
  frontend/src/libs/raidStudio/api/index.ts
  frontend/src/libs/raidStudio/api/squads.ts
  frontend/src/libs/raidStudio/api/users.ts
  frontend/src/libs/raidStudio/client.ts
  frontend/src/utils/api.tsx
Labels: bug

#8 필요없는 코드, api, 패키지 제거
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/app/api/auth/[...nextauth]/route.ts
  frontend/src/app/api/clears/cron/route.ts
  frontend/src/app/api/clears/route.ts
  frontend/src/app/api/lostark/characters/[characterName]/route.ts
  frontend/src/app/api/squads/[id]/characters/route.ts
  frontend/src/app/api/squads/[id]/code/route.ts
  frontend/src/app/api/squads/[id]/members/route.ts
  frontend/src/app/api/squads/join/[code]/route.ts
  frontend/src/app/api/squads/route.ts
  frontend/src/app/api/users/me/characters/reload/route.ts
  frontend/src/app/api/users/me/characters/route.ts
  frontend/src/app/api/users/me/route.ts
  frontend/src/app/api/users/me/squads/route.ts
  frontend/src/app/studio/my/characters/page.tsx
  frontend/src/features/user/UserCharacterNameForm/UserCharacterNameForm.tsx
  frontend/src/hooks/useAPI.ts
  frontend/src/libs/auth/index.ts
  frontend/src/libs/db/collections.ts
  frontend/src/libs/db/index.ts
  frontend/src/libs/lostark/api/characters.ts
  frontend/src/libs/lostark/api/index.ts
  frontend/src/libs/lostark/client.ts
  frontend/src/libs/raidStudio/api/clears.ts
  frontend/src/libs/raidStudio/api/index.ts
  frontend/src/libs/raidStudio/api/squads.ts
  frontend/src/libs/raidStudio/api/users.ts
  frontend/src/libs/raidStudio/client.ts
  frontend/src/utils/api.tsx
Labels: bug

#9 릴레이션 가져오는 api 지원을 위한 FK에 PK 추가
  supabase/migrations/20231111194852_fk_to_pk.sql
Labels: bug

#10 Dependabot 보안 패치 수동 해결 (@babel/traverse: 7.23.2, postcss: 8.4.31)
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: dependencies

#11 Dependabot 보안 패치 수동 해결 (@babel/traverse: 7.23.2, postcss: 8.4.31)
  frontend/package.json
  frontend/pnpm-lock.yaml
  supabase/migrations/20231111194852_fk_to_pk.sql
Labels: dependencies

#13 nextjs 14 업데이트
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: dependencies

#14 캐릭터 클래스 이미지 변경 (svg)
  frontend/src/app/favicon.ico
  frontend/src/assets/images/class/emblem_arcana.png
  frontend/src/assets/images/class/emblem_arcana.svg
  frontend/src/assets/images/class/emblem_bard.png
  frontend/src/assets/images/class/emblem_bard.svg
  frontend/src/assets/images/class/emblem_battle_master.png
  frontend/src/assets/images/class/emblem_battle_master.svg
  frontend/src/assets/images/class/emblem_battle_master_male.png
  frontend/src/assets/images/class/emblem_battle_master_male.svg
  frontend/src/assets/images/class/emblem_berserker.png
  frontend/src/assets/images/class/emblem_berserker.svg
  frontend/src/assets/images/class/emblem_berserker_female.png
  frontend/src/assets/images/class/emblem_berserker_female.svg
  frontend/src/assets/images/class/emblem_blade.png
  frontend/src/assets/images/class/emblem_blade.svg
  frontend/src/assets/images/class/emblem_blaster.png
  frontend/src/assets/images/class/emblem_blaster.svg
  frontend/src/assets/images/class/emblem_demonic.png
  frontend/src/assets/images/class/emblem_demonic.svg
  frontend/src/assets/images/class/emblem_destroyer.png
  frontend/src/assets/images/class/emblem_destroyer.svg
  frontend/src/assets/images/class/emblem_devil_hunter.png
  frontend/src/assets/images/class/emblem_devil_hunter.svg
  frontend/src/assets/images/class/emblem_devil_hunter_female.png
  frontend/src/assets/images/class/emblem_devil_hunter_female.svg
  frontend/src/assets/images/class/emblem_elemental_master.png
  frontend/src/assets/images/class/emblem_elemental_master.svg
  frontend/src/assets/images/class/emblem_force_master.png
  frontend/src/assets/images/class/emblem_force_master.svg
  frontend/src/assets/images/class/emblem_hawk_eye.png
  frontend/src/assets/images/class/emblem_hawk_eye.svg
  frontend/src/assets/images/class/emblem_holyknight.png
  frontend/src/assets/images/class/emblem_holyknight.svg
  frontend/src/assets/images/class/emblem_infighter.png
  frontend/src/assets/images/class/emblem_infighter.svg
  frontend/src/assets/images/class/emblem_lance_master.png
  frontend/src/assets/images/class/emblem_lance_master.svg
  frontend/src/assets/images/class/emblem_reaper.png
  frontend/src/assets/images/class/emblem_reaper.svg
  frontend/src/assets/images/class/emblem_scouter.png
  frontend/src/assets/images/class/emblem_scouter.svg
  frontend/src/assets/images/class/emblem_soul_eater.png
  frontend/src/assets/images/class/emblem_soul_eater.svg
  frontend/src/assets/images/class/emblem_summoner.png
  frontend/src/assets/images/class/emblem_summoner.svg
  frontend/src/assets/images/class/emblem_warlord.png
  frontend/src/assets/images/class/emblem_warlord.svg
  frontend/src/assets/images/class/emblem_weather_artist.png
  frontend/src/assets/images/class/emblem_weather_artist.svg
  frontend/src/assets/images/class/emblem_yinyangshi.png
  frontend/src/assets/images/class/emblem_yinyangshi.svg
  frontend/src/components/Header/Header.tsx
  frontend/src/components/HeaderNavigationMenu/HeaderNavigationMenu.tsx
Labels: enhancement

#15 내 공격대 선택 컴포넌트 동작 버그 수정
  frontend/src/apis/squads.ts
  frontend/src/components/Select/Select.tsx
  frontend/src/features/squad/MySquadSelect/MySquadSelect.tsx
  frontend/src/stores/selectedSquadIdAtom.ts
  frontend/src/stores/userAtom.ts
  frontend/src/types/squads.types.ts
Labels: bug

#16 캐릭터 클래스 이미지 변경 후 적용이 안되던 버그 수정
  frontend/src/assets/images/logo.png
  frontend/src/features/character/CharacterClassIcon/CharacterClassIcon.tsx
Labels: bug

#17 studio 하위 페이지 ui/ux 개선
  frontend/panda.config.ts
  frontend/src/apis/characters.ts
  frontend/src/app/providers.tsx
  frontend/src/app/studio/layout.tsx
  frontend/src/app/studio/my/characters/page.tsx
  frontend/src/app/studio/squad/characters/page.tsx
  frontend/src/components/CommandMenu/CommandMenu.tsx
  frontend/src/features/character/CharacterCard/CharacterCard.tsx
  frontend/src/features/character/CharacterCardListWithUser/CharacterCardListWithUser.tsx
  frontend/src/features/character/MyCharactersReloadButton/MyCharactersReloadButton.tsx
  frontend/src/features/motion/SidebarMotion/SidebarMotion.tsx
  frontend/src/features/raid/RaidTodoList/RaidTodoList.tsx
  frontend/src/features/user/CurrentUserProfileDropdownMenu/CurrentUserProfileDropdownMenu.tsx
Labels: enhancement

#18 헤더 메뉴 버튼 뒷 배경 제거
  frontend/src/components/HeaderNavigationMenu/HeaderNavigationMenu.tsx
Labels: enhancement

#20 squad page 검색 기능 추가
  frontend/src/apis/squads.ts
  frontend/src/app/squad/list/page.tsx
  raid-studio.code-workspace
Labels: enhancement

#21 squad page 검색 결과 없음 추가
  frontend/src/app/squad/list/page.tsx
Labels: enhancement
